/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */

public class VentanaVoluntariosBDR extends javax.swing.JFrame {

//    String nomArchivo = "listadoDeportistas.dat";
//    MiniAgendaBDR miniAgenda = new MiniAgendaBDR();
//    
//    String[] nomColumnas = {"NOMBRE",
//        "DEPORTE",
//        "A�O NAC.",
//        "ALTURA"};
//    Object[][] matrizDatos = {
////        {"Carolina Mar�n", "B�dminton", 1993, 1.72},
////        {"Pau Gasol", "Baloncesto", 1980, 2.15},
////        {"Rafa Nadal", "Tenis", 1986, 1.85},
//    };
    
    
//    DefaultTableModel dtm = new DefaultTableModel(matrizDatos, nomColumnas);

    
    /**
     * Creates new form VentanaMiniAgendaBDR
     */
    public VentanaVoluntariosBDR()  {
        initComponents();
//        miniAgenda.conectarBD();
//        
//         dtm = new DefaultTableModel(matrizDatos, nomColumnas) {
//        @Override
//        public boolean isCellEditable(int fila, int columna) {
//            return false;
//
//            }

        };
//        // Establecimiento de los datos a la tabla
//        jDatos.setModel(dtm);
//        // Configuraci�n del tipo de selecci�n de la tabla
//
//        jDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
//        // Ajuste de anchos
//
//        jDatos.getColumn("NOMBRE").setPreferredWidth(260);
//
//        jDatos.getColumn("DEPORTE").setPreferredWidth(160);
//
//        jDatos.getColumn("A�O NAC.").setPreferredWidth(100);
//
//        jDatos.getColumn("ALTURA").setPreferredWidth(200);
//        
//        jDatos.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
//        @Override
//        public void valueChanged(javax.swing.event.ListSelectionEvent e) {
//                int selectedRow = jDatos.getSelectedRow(); // Obtener la fila seleccionada
//                if (selectedRow != -1) { // Verificar que se haya seleccionado una fila v�lida
//                    // Extraer los datos de la fila seleccionada
//                    String nombre = jDatos.getValueAt(selectedRow, 0).toString(); // Columna "NOMBRE"
//                    String deporte = jDatos.getValueAt(selectedRow, 1).toString(); // Columna "DEPORTE"
//                    String anoNacimiento = jDatos.getValueAt(selectedRow, 2).toString(); // Columna "A�O NAC."
//                    String altura = jDatos.getValueAt(selectedRow, 3).toString(); // Columna "ALTURA"
//
//                    // Asignar los datos a los campos correspondientes
//                    jTextFieldNombre.setText(nombre); // Campo para el nombre
//                    jTextFieldDeporte.setText(deporte); // Campo para el deporte
//                    jTextFieldA�oNacimiento.setText(anoNacimiento); // Campo para el a�o de nacimiento
//                    jTextFieldAltura.setText(altura); // Campo para la altura
//                }
//        }
//    });
//        // Mostrar los datos del TreeSet en la tabla
//
//        actualizaTabla();
//    }
//    
//    
//    
//    private void actualizaTabla() {
//    matrizDatos = miniAgenda.obtenerTodo();
//
////    if (matrizDatos != null) {
//        // Actualizar el modelo de la tabla
//        dtm.setDataVector(matrizDatos, nomColumnas);
//        jDatos.setModel(dtm);
////    } else {
////        System.err.println("Error: No se pudieron obtener los datos de la base de datos.");
////    }
//}
//    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDeporte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAñoNacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jCheck_Vaciar = new javax.swing.JCheckBox();
        jButton_VaciarCampos = new javax.swing.JButton();
        jButton_Anadir = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonBorrarPorNombre = new javax.swing.JButton();
        jButtonBorrarSeleccionado = new javax.swing.JButton();
        jButtonBorrarTodo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonGuardarFichero = new javax.swing.JButton();
        jButtonCargarFichero = new javax.swing.JButton();
        jButtonCargarEjemplos = new javax.swing.JButton();
        j = new javax.swing.JScrollPane();
        jDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Nombre y apellidos: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Raza: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Fecha ingreso: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Estado:");

        jTextFieldAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlturaActionPerformed(evt);
            }
        });

        jCheck_Vaciar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jCheck_Vaciar.setText("Vaciar después de añadir");
        jCheck_Vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck_VaciarActionPerformed(evt);
            }
        });

        jButton_VaciarCampos.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jButton_VaciarCampos.setText("Vaciar campos");
        jButton_VaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VaciarCamposActionPerformed(evt);
            }
        });

        jButton_Anadir.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton_Anadir.setText("Añadir");
        jButton_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnadirActionPerformed(evt);
            }
        });

        jButton_Actualizar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton_Actualizar.setText("Actualizar");
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAñoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldDeporte)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheck_Vaciar)
                                .addGap(45, 45, 45)
                                .addComponent(jButton_VaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButton_Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAñoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheck_Vaciar)
                    .addComponent(jButton_VaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jButtonBorrarPorNombre.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jButtonBorrarPorNombre.setText("Borrar por nombre");
        jButtonBorrarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarPorNombreActionPerformed(evt);
            }
        });

        jButtonBorrarSeleccionado.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jButtonBorrarSeleccionado.setText("Borrar seleccionado");
        jButtonBorrarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarSeleccionadoActionPerformed(evt);
            }
        });

        jButtonBorrarTodo.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jButtonBorrarTodo.setText("Borrar todo");
        jButtonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonBorrarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButtonBorrarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jButtonGuardarFichero.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jButtonGuardarFichero.setText("Guardar en fichero");
        jButtonGuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarFicheroActionPerformed(evt);
            }
        });

        jButtonCargarFichero.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jButtonCargarFichero.setText("Cargar de fichero");

        jButtonCargarEjemplos.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jButtonCargarEjemplos.setText("Cargar ejemplos");
        jButtonCargarEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarEjemplosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButtonGuardarFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jButtonCargarFichero)
                .addGap(119, 119, 119)
                .addComponent(jButtonCargarEjemplos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCargarEjemplos, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarFichero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCargarFichero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        jDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        j.setViewportView(jDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheck_VaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck_VaciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheck_VaciarActionPerformed

    private void jButton_VaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VaciarCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VaciarCamposActionPerformed

    private void jButtonBorrarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarPorNombreActionPerformed
//        miniAgenda.borrarPorNombre();
//        actualizaTabla();
    }//GEN-LAST:event_jButtonBorrarPorNombreActionPerformed

    private void jButtonBorrarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarSeleccionadoActionPerformed
         
    }//GEN-LAST:event_jButtonBorrarSeleccionadoActionPerformed

    private void jTextFieldAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaActionPerformed

    private void jButtonCargarEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarEjemplosActionPerformed
//       miniAgenda.cargarEjemplos();
//       actualizaTabla();
    }//GEN-LAST:event_jButtonCargarEjemplosActionPerformed

    private void jButtonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodoActionPerformed
//         miniAgenda.borrarTodo();
//         actualizaTabla();
         
    }//GEN-LAST:event_jButtonBorrarTodoActionPerformed

    private void jButton_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnadirActionPerformed
        // Obtener los datos de los campos de texto
//    String nomYApe = jTextFieldNombre.getText().trim(); // Nombre y apellidos
//    String deporte = jTextFieldDeporte.getText().trim(); // Deporte
//    int anoNacimiento;
//    float altura;
//
//    try {
//        anoNacimiento = Integer.parseInt(jTextFieldA�oNacimiento.getText().trim()); // A�o de nacimiento
//        altura = Float.parseFloat(jTextFieldAltura.getText().trim());       // Altura
//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(this, "Por favor, introduce n�meros v�lidos para el a�o y la altura.");
//        return;
//    }
//
//    // Llamar al m�todo para a�adir el deportista
//    boolean exito = miniAgenda.a�adirUno(nomYApe, deporte, anoNacimiento, altura);
//
//    if (exito) {
//        // Actualizar la tabla
//        actualizaTabla();
//        if (jCheck_Vaciar.isSelected()) {
//        // Limpiar los campos de texto
//        jTextFieldNombre.setText("");
//        jTextFieldDeporte.setText("");
//        jTextFieldA�oNacimiento.setText("");
//        jTextFieldAltura.setText("");
//        }
//
//        
//      
//
//        JOptionPane.showMessageDialog(this, "Deportista a�adido correctamente.");
//    } else {
//        JOptionPane.showMessageDialog(this, "Error al a�adir el deportista.");
//    }
    }//GEN-LAST:event_jButton_AnadirActionPerformed

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed
//        actualizaTabla();
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void jButtonGuardarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarFicheroActionPerformed
//       miniAgenda.cargarFichero();
       
    }//GEN-LAST:event_jButtonGuardarFicheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(VentanaVoluntariosBDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(VentanaVoluntariosBDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(VentanaVoluntariosBDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(VentanaVoluntariosBDR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new VentanaVoluntariosBDR().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane j;
    private javax.swing.JButton jButtonBorrarPorNombre;
    private javax.swing.JButton jButtonBorrarSeleccionado;
    private javax.swing.JButton jButtonBorrarTodo;
    private javax.swing.JButton jButtonCargarEjemplos;
    private javax.swing.JButton jButtonCargarFichero;
    private javax.swing.JButton jButtonGuardarFichero;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Anadir;
    private javax.swing.JButton jButton_VaciarCampos;
    private javax.swing.JCheckBox jCheck_Vaciar;
    private javax.swing.JTable jDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldAñoNacimiento;
    private javax.swing.JTextField jTextFieldDeporte;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
